# This is a basic workflow to help you get started with Actions

name: CI Caller

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branc

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      deployment_type: primary
    secrets: inherit
    
  cd:
    uses: ./.github/workflows/cd.yml
    needs: [ci]
    strategy:
      matrix:
        include:
          - deployment_type: primary
          - deployment_type: secondary
    with:
      deployment_type: ${{ matrix.deployment_type }}
    secrets: inherit
