# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      deployment_type:
        description: 'Select deployment_type'
        required: true
        default: primary
        type: choice
        options:
          - primary
          - secondary
  push:
    branches: 
     - main
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Set deployment variables
        env: 
          DEPLOYMENTS: ${{ vars.DEPLOYMENTS }}
          DEPLOYMENT_TYPE: ${{ inputs.deployment_type || 'primary'}}
        run: |
          echo $DEPLOYMENTS > deployments.json
          cat deployments.json | jq -r '.${{ env.DEPLOYMENT_TYPE }}.traffic_enabled'
          echo "REGION=$(cat deployments.json | jq -r '.${{ env.DEPLOYMENT_TYPE }}.region')" >> $GITHUB_ENV
          echo "TRAFFIC_ENABLED=$(cat deployments.json | jq -r '.${{ env.DEPLOYMENT_TYPE }}.traffic_enabled')" >> $GITHUB_ENV
        

      - name: Check deployment variables
        run: |
          echo ${{ env.REGION }}
          echo $TRAFFIC_ENABLED
      
