# This is a basic workflow to help you get started with Actions

name: Production APAC

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branc

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: caller-prod-apac
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      environment: prod-apac
      deployment_type: primary
    secrets: inherit

  cd:
    uses: ./.github/workflows/cd.yml
    needs: [ci]
    with:
      environment: prod-apac
      deployment_type: primary
    secrets: inherit
